#action.yaml
name: 'Custom GitHub Action'
description: 'GA takes inputs and returns outputs'
inputs:
  num:
    discription: 'Enter a number'
    required: true
    default: "1"
outputs:  
  num_squared:
    description: 'Square of the input'
    # need to specify the extra 'value' field for 'composite' actions
    value: ${{ steps.get_square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup_python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
        echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get_square
      run: python src/get_num_square.py
      shell: bash

